object_storage: API + operation changes
aiven/rohmu pull request #101
Opened 2023-04-17 08:12 UTC by fingon

- Add get_contents_to_file/string to base class

  (No API change, just implementation simpliciy)

  Ultimately only get_contents_to_fileobj is the interesting one (if we don't implement proper parallel multipart upload anyway), and the other two can just use that.

- Add store_file_from_memory, store_file_from_disk to base class

  NOTE: Backward incompatible API change - require keyword arguments also in store_file_from_disk (all Aiven code is fine with it, and we want this going forward)

  NOTE: Handling of 'metadata' varied by functions (in some it was keyword argument, in others not); made it non-keyword third argument in all 3 store variants. (This is backwards compatible, as restrictions were just loosened.)

- operation tracking changes/fixes

  - documented the operations somewhat

  - added multipart abort

  - simplified the list too; we don't really care about the type of get_file that is used (for example); also storing multipart chunks on S3 is just implementation detail and part of store_file API call

  - change operation so that it has both count and size metric (size one is populated only for metrics supplied with size)

  - use increase for both, the old gauge for size dropped data if there was more than one entry per metrics interval

# About this change - What it does

Resolves: #xxxxx

# Why this way

2023-04-19 05:05 UTC, ilpon reviewed
Looks good to me, but needs someone else to review.

2023-04-20 10:29 UTC, kmichel-aiven approved these changes
A few more parameter and return type hints on the modified functions would have been good, but there is less code that before, so still technically better than yesterday.

2023-04-20 11:09 UTC, rikonen requested changes

2023-04-20 11:09 UTC, rikonen commented on rohmu/object_storage/base.py
> +                upload_progress_fn=self._incremental_to_proportional_progress(cb=progress_fn, size=size),
This looks to be incorrect behavior for `S3Transfer` as that reports the total number of bytes sent every time instead of delta.

2023-04-20 11:22 UTC, rikonen approved these changes
True, I didn't expand the lines and missed the `_proportional_to_incremental_progress` call there, just checked the `multipart_upload_file_object` implementation

2023-04-20 11:24 UTC, merged