Bump to version 1.0.11
aiven/rohmu pull request #114
Opened 2023-06-14 11:42 UTC by giacomo-alzetta-aiven

# About this change - What it does

Bumping to version 1.0.11.

Somehow main is at 1.0.9 but PyPI has version 1.0.10 available... I guess in the last release the tag was pushed and the branch deleted instead of being merged into main?

# Why this way

I need a new version so that we can update robjecter dependency on rohmu to use new transfer pool.

2023-06-14 19:36 UTC, sjamgade commented
after looking at the changes, we dropped 3.7 (officially) which would warrant a major bump

2023-06-15 03:55 UTC, fingon requested changes
Sumit has a point - I think this should be really 1.1 as it is backwards incompatible in a sense that it drops Python 3.7 support.

2023-06-15 07:00 UTC, giacomo-alzetta-aiven commented
> Sumit has a point - I think this should be really 1.1 as it is backwards incompatible in a sense that it drops Python 3.7 support.

I'm not sure. In the end we do mark the versions supported so pip used on python 3.7 won't ever try to install the incompatible version... that's only an issue for people manually installing it... but I don't know how relevant is semantic versioning.

In any case I guess I can change this to `1.1.0` or `2.0.0` as you like.

2023-06-15 08:34 UTC, fingon approved these changes

2023-06-15 09:38 UTC, sjamgade approved these changes

2023-06-15 09:38 UTC, merged